name: CI Workflow

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'
    # Your build steps go here
    
    - name: Notify the commit on Telegram
      uses: EverythingSuckz/github-telegram-notify@main
      with:
        bot_token: '${{ secrets.TELEGRAM_BOT_TOKEN }}'
        chat_id: '${{ secrets.TELEGRAM_CHAT_ID }}'
        topic_id: '${{ secrets.TOPIC_ID }}'
